<?php
function getEmojis(){
    $smileys = array(
        
        //	smiley			image name				alt
        
        ':-)'			=>	array('grin.gif',				'grin'),
        ':lol:'			=>	array('lol.gif',				'LOL'),
        ':cheese:'		=>	array('cheese.gif',				'cheese'),
        ':)'			=>	array('smile.gif',				'smile'),
        ';-)'			=>	array('wink.gif',				'wink'),
        ';)'			=>	array('wink.gif',				'wink'),
        ':smirk:'		=>	array('smirk.gif',				'smirk'),
        ':roll:'		=>	array('rolleyes.gif',		'rolleyes'),
        ':-S'			=>	array('confused.gif',		'confused'),
        ':wow:'			=>	array('surprise.gif',		'surprised'),
        ':bug:'			=>	array('bigsurprise.gif','big surprise'),
        ':-P'			=>	array('tongue_laugh.gif','tongue laugh'),
        '%-P'			=>	array('tongue_rolleye.gif','tongue rolleye'),
        ';-P'			=>	array('tongue_wink.gif','tongue wink'),
        ':P'			=>	array('raspberry.gif',		'raspberry'),
        ':blank:'		=>	array('blank.gif',				'blank stare'),
        ':long:'		=>	array('longface.gif',		'long face'),
        ':ohh:'			=>	array('ohh.gif',				'ohh'),
        ':grrr:'		=>	array('grrr.gif',				'grrr'),
        ':gulp:'		=>	array('gulp.gif',				'gulp'),
        '8-/'			=>	array('ohoh.gif',				'oh oh'),
        ':down:'		=>	array('downer.gif',				'downer'),
        ':red:'			=>	array('embarrassed.gif','red face'),
        ':sick:'		=>	array('sick.gif',				'sick'),
        ':shut:'		=>	array('shuteye.gif',		'shut eye'),
        ':-/'			=>	array('hmm.gif',				'hmmm'),
        '>:('			=>	array('mad.gif',				'mad'),
        ':mad:'			=>	array('mad.gif',				'mad'),
        '>:-('			=>	array('angry.gif',				'angry'),
        ':angry:'		=>	array('angry.gif',				'angry'),
        ':zip:'			=>	array('zip.gif',				'zipper'),
        ':kiss:'		=>	array('kiss.gif',				'kiss'),
        ':ahhh:'		=>	array('shock.gif',				'shock'),
        ':coolsmile:'	=>	array('shade_smile.gif','cool smile'),
        ':coolsmirk:'	=>	array('shade_smirk.gif','cool smirk'),
        ':coolgrin:'	=>	array('shade_grin.gif',		'cool grin'),
        ':coolhmm:'		=>	array('shade_hmm.gif',		'cool hmm'),
        ':coolmad:'		=>	array('shade_mad.gif',		'cool mad'),
        ':coolcheese:'	=>	array('shade_cheese.gif','cool cheese'),
        ':vampire:'		=>	array('vampire.gif',		'vampire'),
        ':snake:'		=>	array('snake.gif',				'snake'),
        ':exclaim:'		=>	array('exclaim.gif',		'excaim'),
        ':question:'	=>	array('question.gif',		'question'),
    );
    return $smileys;
}